version: '3.7'
services:
    wordpress:

        image: wordpress:latest

        ports:
            - "8080:80"
        restart: always
        environment:
            WORDPRESS_DB_HOST: 10.88.2.117
            WORDPRESS_DB_USER: wordpressuser
            WORDPRESS_DB_PASSWORD: wordpress
            WORDPRESSS_DB_NAME: wordpress
